# Generated by Django 2.1.15 on 2020-06-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.PositiveIntegerField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('round_trip', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Customer')),
                ('departure_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Flight')),
                ('return_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.PositiveIntegerField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('round_trip', models.BooleanField(default=False)),
                ('session_guid', models.UUIDField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Customer')),
                ('departure_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Flight')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Reservation')),
                ('return_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSeat_Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Flight')),
                ('plane_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.PlaneSeat')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Reservation_Staging')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservationperm',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservationperm',
            name='departure_flight',
        ),
        migrations.RemoveField(
            model_name='reservationperm',
            name='return_flight',
        ),
        migrations.RemoveField(
            model_name='reservationstaged',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservationstaged',
            name='departure_flight',
        ),
        migrations.RemoveField(
            model_name='reservationstaged',
            name='return_flight',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservationseat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
        ),
        migrations.DeleteModel(
            name='ReservationPerm',
        ),
        migrations.DeleteModel(
            name='ReservationStaged',
        ),
        migrations.AddField(
            model_name='passenger_staging',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Reservation_Staging'),
        ),
    ]
