# Generated by Django 2.1.15 on 2020-05-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
            preserve_default=False,
        ),
    ]
