# Generated by Django 2.1.15 on 2020-06-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200606_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_staging',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationseat_staging',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='reservationseat_staging',
            name='plane_seat',
        ),
        migrations.RemoveField(
            model_name='reservationseat_staging',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation_staging',
            name='departure_flight',
        ),
        migrations.RemoveField(
            model_name='reservation_staging',
            name='return_flight',
        ),
        migrations.RemoveField(
            model_name='reservation_staging',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='reservation_staging',
            name='departure_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Airport'),
        ),
        migrations.AddField(
            model_name='reservation_staging',
            name='return_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Airport'),
        ),
        migrations.DeleteModel(
            name='Passenger_Staging',
        ),
        migrations.DeleteModel(
            name='ReservationSeat_Staging',
        ),
    ]
