# Generated by Django 2.1.15 on 2020-05-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200525_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Flight'),
            preserve_default=False,
        ),
    ]
