# Generated by Django 2.1.15 on 2020-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200607_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_staging',
            old_name='return_airport',
            new_name='arrival_airport',
        ),
        migrations.AddField(
            model_name='reservation_staging',
            name='departure_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation_staging',
            name='return_date',
            field=models.DateField(auto_now=True),
        ),
    ]
