# Generated by Django 2.1.15 on 2020-05-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='flight',
            new_name='departure_flight',
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Flight'),
            preserve_default=False,
        ),
    ]
