# Generated by Django 2.1.15 on 2020-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200530_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='departure_flight',
        ),
        migrations.AddField(
            model_name='reservation',
            name='departure_flight',
            field=models.ManyToManyField(to='reservations.Flight'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='return_flight',
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_flight',
            field=models.ManyToManyField(to='reservations.Flight'),
        ),
    ]
