# Generated by Django 2.1.15 on 2020-06-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200624_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='plane_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.PlaneModel'),
        ),
        migrations.AddField(
            model_name='planemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
