# Generated by Django 2.1.15 on 2020-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200607_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_staging',
            name='round_trip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
