# Generated by Django 2.1.15 on 2020-05-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200530_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='return_flight',
        ),
    ]
