# Generated by Django 2.1.15 on 2020-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200627_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planemodel',
            old_name='name',
            new_name='make_name',
        ),
        migrations.AddField(
            model_name='planemodel',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
