# Generated by Django 2.1.15 on 2020-06-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200627_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane_model',
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.Plane'),
        ),
    ]
