# Generated by Django 2.1.15 on 2020-07-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200628_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_retail', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.Flight')),
                ('service_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservations.ServiceClass')),
            ],
        ),
    ]
