# Generated by Django 2.1.15 on 2020-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200530_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_flight',
            field=models.ManyToManyField(to='reservations.Flight'),
        ),
    ]
