# Generated by Django 2.1.15 on 2020-07-07 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_flightretail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_main',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 27, 50, 433866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation_main',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 27, 50, 433866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation_staging',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 27, 50, 433866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation_staging',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 27, 50, 433866, tzinfo=utc)),
        ),
    ]
