# Generated by Django 2.1.15 on 2020-07-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20200707_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeseat',
            name='cabin_position',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
