# Generated by Django 2.1.15 on 2020-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_planeseat_cabin_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_main',
            name='assignment_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passenger_staging',
            name='assignment_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
