# Generated by Django 2.1.15 on 2020-07-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20200711_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_main',
            name='assignment_number',
        ),
        migrations.RemoveField(
            model_name='passenger_staging',
            name='assignment_number',
        ),
    ]
