# Generated by Django 2.1.15 on 2020-07-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_passenger_main_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_main',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation_Main'),
            preserve_default=False,
        ),
    ]
