# Generated by Django 2.1.15 on 2020-08-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_passenger_main_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight_type', models.CharField(max_length=100)),
                ('log_time', models.DateField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Passenger_Main')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Reservation_Main')),
            ],
        ),
    ]
