# Generated by Django 2.1.15 on 2020-08-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservation_staging_session_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsession',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservationsession',
            name='number_of_passengers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservationsession',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
